export const rotatingCookieFlavorsHref = '/rotating-cookie-flavors'
export const menuHref = '/menu'
export const blogHref = '/blog'
export const discussionBoardHref = '/discussion-board'
export const reviewsHref = '/reviews'
export const blessingsNetworkHref = '/blessings-network'
