/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Business owner workflow status. Paid checkout creates orders as Processing; update this as the order is fulfilled, cancelled, or refunded.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    customers: Customer;
    'email-verification-starts': EmailVerificationStart;
    'phone-verification-starts': PhoneVerificationStart;
    'discussion-nodes': DiscussionNode;
    'discussion-edges': DiscussionEdge;
    'awareness-marks': AwarenessMark;
    reviews: Review;
    'blessings-network-owners': BlessingsNetworkOwner;
    'blessings-network-questions': BlessingsNetworkQuestion;
    'blessings-network-answers': BlessingsNetworkAnswer;
    'blessings-network-owner-posts': BlessingsNetworkOwnerPost;
    pages: Page;
    posts: Post;
    'flavor-rotations': FlavorRotation;
    categories: Category;
    media: Media;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    customers: {
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'email-verification-starts': EmailVerificationStartsSelect<false> | EmailVerificationStartsSelect<true>;
    'phone-verification-starts': PhoneVerificationStartsSelect<false> | PhoneVerificationStartsSelect<true>;
    'discussion-nodes': DiscussionNodesSelect<false> | DiscussionNodesSelect<true>;
    'discussion-edges': DiscussionEdgesSelect<false> | DiscussionEdgesSelect<true>;
    'awareness-marks': AwarenessMarksSelect<false> | AwarenessMarksSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'blessings-network-owners': BlessingsNetworkOwnersSelect<false> | BlessingsNetworkOwnersSelect<true>;
    'blessings-network-questions': BlessingsNetworkQuestionsSelect<false> | BlessingsNetworkQuestionsSelect<true>;
    'blessings-network-answers': BlessingsNetworkAnswersSelect<false> | BlessingsNetworkAnswersSelect<true>;
    'blessings-network-owner-posts': BlessingsNetworkOwnerPostsSelect<false> | BlessingsNetworkOwnerPostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'flavor-rotations': FlavorRotationsSelect<false> | FlavorRotationsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    brand: Brand;
    header: Header;
    footer: Footer;
    'blog-page-content': BlogPageContent;
    'discussion-board-content': DiscussionBoardContent;
  };
  globalsSelect: {
    brand: BrandSelect<false> | BrandSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'blog-page-content': BlogPageContentSelect<false> | BlogPageContentSelect<true>;
    'discussion-board-content': DiscussionBoardContentSelect<false> | DiscussionBoardContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers: Customer;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword:
    | {
        email: string;
      }
    | {
        username: string;
      };
  login:
    | {
        email: string;
        password: string;
      }
    | {
        password: string;
        username: string;
      };
  registerFirstUser: {
    password: string;
    username?: string;
    email?: string;
  };
  unlock:
    | {
        email: string;
      }
    | {
        username: string;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name?: string | null;
  /**
   * Stored in normalized international format for phone login and verification.
   */
  phone?: string | null;
  phoneVerifiedAt?: string | null;
  /**
   * Stripe Customer ID used to link this Payload customer to Stripe payments.
   */
  stripeCustomerID?: string | null;
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (number | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (number | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username?: string | null;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * Paid customer orders. Open an order to update fulfillment status and review customer contact, items, and delivery details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        /**
         * For tray-builder products, store which child products were picked for this tray and how many of each.
         */
        batchSelections?:
          | {
              product: number | Product;
              quantity: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (number | null) | Customer;
  customerEmail?: string | null;
  transactions?: (number | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: 'USD' | null;
  /**
   * Derived guest checkout contact method. The official ecommerce plugin still requires email for guest purchases.
   */
  guestContactMethod?: ('email' | 'phone') | null;
  /**
   * Derived guest checkout contact value. This is app-level groundwork for a future email-or-phone guest flow.
   */
  guestContactValue?: string | null;
  accessToken?: string | null;
  /**
   * Set automatically after the new-order email is sent to the business owner.
   */
  ownerNotificationSentAt?: string | null;
  /**
   * Stripe PaymentIntent used as the checkout idempotency key.
   */
  stripePaymentIntentID?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Short product story for the product page and supporting storefront copy.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Long-form copy shown inside expandable menu cards. Use this when you want a more persuasive, blog-like section without creating a dedicated product page.
   */
  menuExpandedPitch?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Product image gallery. The first image is the main storefront image, so put the best primary photo first.
   */
  gallery?:
    | {
        /**
         * Choose the photo that should appear for this gallery item.
         */
        image: number | Media;
        /**
         * Only use this when variants are enabled and the image belongs to one specific option.
         */
        variantOption?: (number | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional long-form sections below the main product details. Use these for ingredient notes, FAQs, extra selling copy, or supporting media.
   */
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  /**
   * Display details for the cookie cards and cookie detail art. This is where the business owner edits the short cookie tags, summary, and the handwritten-style ingredient note popup.
   */
  poster?: {
    /**
     * Short line used under the cookie title on poster-style storefront cards.
     */
    subtitle?: string | null;
    /**
     * Short all-caps tags shown as visual pills, such as BROWN BUTTER or CHEWY.
     */
    chips?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Highlighted label shown above the cookie title on the poster detail page.
     */
    label?: string | null;
    /**
     * Background color for the poster label, usually a hex value like #f6c58f.
     */
    labelTone?: string | null;
    /**
     * Short marketing summary used on the poster card and poster detail page.
     */
    summary?: string | null;
    /**
     * Small label for the translucent scene button that opens the baker-note ingredient popup.
     */
    infoButtonLabel?: string | null;
    /**
     * Deprecated. Use Info Dialog Text instead so the storefront can render normal paragraphs.
     */
    ingredientsNoteTitle?: string | null;
    /**
     * Deprecated. Use Info Dialog Text instead so the storefront can render normal paragraphs.
     */
    ingredientsIntro?: string | null;
    /**
     * Rich text shown in the cookie info speech bubble. Use paragraphs and bold text for flavor notes, handling notes, and allergy warnings.
     */
    receiptBody?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Deprecated. Kept only to preserve existing database schema; the storefront now uses Info Dialog Text.
     */
    receiptTitle?: string | null;
    /**
     * Deprecated. Kept only to preserve existing database schema; warnings should now be written directly in Info Dialog Text.
     */
    receiptWarnings?:
      | {
          tone: 'info' | 'caution' | 'danger';
          label: string;
          message: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Deprecated. Use Info Dialog Text instead; the old row layout could collide on narrow cards.
     */
    ingredients?:
      | {
          name: string;
          detail?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Stock count for simple products. If you enable variants, manage stock on each variant instead of here.
   */
  inventory?: number | null;
  /**
   * Turn this on when one product needs selectable options such as size, flavor, filling, or color.
   */
  enableVariants?: boolean | null;
  /**
   * Choose which kinds of options customers can pick, for example size, flavor, or pickup package.
   */
  variantTypes?: (number | VariantType)[] | null;
  /**
   * After you choose variant types, create the actual purchasable combinations here with their own price and inventory.
   */
  variants?: {
    docs?: (number | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  /**
   * Short quantity label for menu cards, for example "10 jumbo cookies", "10 cups", or "One tray".
   */
  menuPortionLabel?: string | null;
  /**
   * Use configurable tray when this product is built from child product flavors instead of being added directly. The storefront currently supports single-flavor trays, and custom mix trays can be enabled later without changing the relationship model.
   */
  menuBehavior?: ('simple' | 'batchBuilder') | null;
  /**
   * How many cookies belong in the tray. For today's single-flavor trays, this becomes the quantity of the chosen flavor.
   */
  requiredSelectionCount?: number | null;
  /**
   * Choose which cookie flavors are allowed for this tray. The storefront currently lets the customer pick one of these flavors for the full tray.
   */
  selectableProducts?: (number | Product)[] | null;
  /**
   * Pick other products that should be suggested alongside this one on the storefront.
   */
  relatedProducts?: (number | Product)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Categories group products on the /menu page and help organize the menu for customers and admins.
   */
  categories?: (number | Category)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    poster?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: number;
  _variantOptions_options_order?: string | null;
  variantType: number | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: number;
  label: string;
  name: string;
  options?: {
    docs?: (number | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  /**
   * Write the main promotional message and supporting copy for this call-to-action section.
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  publishedOn?: string | null;
  /**
   * This is the top section of the page. Use it for the main headline, supporting copy, buttons, and an optional lead image.
   */
  hero: {
    /**
     * Choose how visually prominent the top-of-page hero should be. Use None when the page should begin directly with content blocks.
     */
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    /**
     * Write the hero headline and supporting intro copy here.
     */
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Choose the lead image for higher-impact hero styles. It only appears for Medium Impact and High Impact heroes.
     */
    media?: (number | null) | Media;
  };
  /**
   * Blocks are reusable page sections. Use Content for text columns, Call to Action for promo copy and buttons, Media Block for one image or video, Carousel or Archive for product lists, Three Item Grid for exactly three featured products, Banner for short notices, and Form Block to embed a form.
   */
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Short summary shown on the blog list, page hero, and default SEO description.
   */
  excerpt: string;
  authorName: string;
  publishedOn?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * Use this block for one or more text columns, such as story sections, FAQs, values, or side-by-side copy.
   */
  columns?:
    | {
        /**
         * Choose how wide this column should be within the row.
         */
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        /**
         * Add the text content for this column.
         */
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Turn this on if this column should include one link or button.
         */
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  /**
   * Use this block when the section should primarily be one image or video.
   */
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  /**
   * Optional intro copy that appears above the automatically generated product list.
   */
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Choose whether this block should auto-fill from a collection or show a manual selection.
   */
  populateBy?: ('collection' | 'selection') | null;
  /**
   * Choose which collection this automatic list should pull from.
   */
  relationTo?: 'products' | null;
  /**
   * Optional filter: only show products from these categories.
   */
  categories?: (number | Category)[] | null;
  /**
   * Maximum number of products to show in this block.
   */
  limit?: number | null;
  /**
   * Pick the specific products to show when you want a manual list.
   */
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Lower values appear first in /menu sections. Use this to control category order from Admin.
   */
  menuOrder?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  /**
   * Choose whether this carousel should auto-fill from a collection or use a manual product selection.
   */
  populateBy?: ('collection' | 'selection') | null;
  /**
   * Choose which collection this automatic carousel should pull from.
   */
  relationTo?: 'products' | null;
  /**
   * Optional filter: only show products from these categories.
   */
  categories?: (number | Category)[] | null;
  /**
   * Maximum number of products to include in the carousel.
   */
  limit?: number | null;
  /**
   * Pick the specific products to show when you want a manual carousel.
   */
  selectedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: number | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  /**
   * Pick exactly three featured products to display in this section.
   */
  products?: (number | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  /**
   * Choose the tone of the banner message.
   */
  style: 'info' | 'warning' | 'error' | 'success';
  /**
   * Short notice text, such as a promo, update, warning, or service announcement.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  /**
   * Choose which saved form should appear in this section.
   */
  form: number | Form;
  /**
   * Turn this on if the form needs a heading or explanatory copy above it.
   */
  enableIntro?: boolean | null;
  /**
   * Add the heading or instructions that should appear above the form.
   */
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: number;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: number | Product;
  options: (number | VariantOption)[];
  inventory?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        /**
         * For tray-builder products, store which child products were picked for this tray and how many of each.
         */
        batchSelections?:
          | {
              product: number | Product;
              quantity: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'stripe' | null;
  stripe?: {
    customerID?: string | null;
    paymentIntentID?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (number | null) | Customer;
  customerEmail?: string | null;
  order?: (number | null) | Order;
  cart?: (number | null) | Cart;
  amount?: number | null;
  currency?: 'USD' | null;
  /**
   * Derived guest checkout contact method. The official ecommerce plugin still requires email for guest purchases.
   */
  guestContactMethod?: ('email' | 'phone') | null;
  /**
   * Derived guest checkout contact value. This is app-level groundwork for a future email-or-phone guest flow.
   */
  guestContactValue?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: (number | null) | Variant;
        quantity: number;
        /**
         * For tray-builder products, store which child products were picked for this tray and how many of each.
         */
        batchSelections?:
          | {
              product: number | Product;
              quantity: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (number | null) | Customer;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: 'USD' | null;
  /**
   * Guest cart IDs already merged into this cart. Used for retry-safe merges.
   */
  mergedSourceCartIDs?:
    | {
        sourceCartID: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  customer?: (number | null) | Customer;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-verification-starts".
 */
export interface EmailVerificationStart {
  id: number;
  key: string;
  flow: 'signup';
  email: string;
  codeHash: string;
  attempts: number;
  consumedAt?: string | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-verification-starts".
 */
export interface PhoneVerificationStart {
  id: number;
  key: string;
  flow: 'signup' | 'password-reset';
  phone: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussion-nodes".
 */
export interface DiscussionNode {
  id: number;
  tenantId: string;
  isRoot?: boolean | null;
  /**
   * Blank for root topics. Child nodes point to the root topic for fast queries.
   */
  rootNode?: (number | null) | DiscussionNode;
  /**
   * Blank for anonymous testing posts.
   */
  author?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null);
  /**
   * Display name stored on the node. Anonymous test posts can still show a name.
   */
  authorDisplayName?: string | null;
  type: 'question' | 'statement';
  title: string;
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Derived from title, content blocks, and tags for simple search.
   */
  searchText?: string | null;
  moderationStatus: 'visible' | 'hidden';
  /**
   * Stable key used to make public reply submission retries idempotent.
   */
  submissionKey?: string | null;
  moderationReason?: string | null;
  moderatedBy?: (number | null) | Admin;
  moderatedAt?: string | null;
  authorState: 'current' | 'reconsidered';
  reconsideredDueToNode?: (number | null) | DiscussionNode;
  supportCount?: number | null;
  challengeCount?: number | null;
  responseCount?: number | null;
  questionCount?: number | null;
  awarenessCount?: number | null;
  cryCount?: number | null;
  wiltedRoseCount?: number | null;
  childCount?: number | null;
  lastActivityAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussion-edges".
 */
export interface DiscussionEdge {
  id: number;
  tenantId: string;
  rootNode: number | DiscussionNode;
  fromNode: number | DiscussionNode;
  toNode: number | DiscussionNode;
  toBlockIds?:
    | {
        blockId: string;
        id?: string | null;
      }[]
    | null;
  type: 'responds_to' | 'asks_about' | 'supports' | 'challenges' | 'related_to';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awareness-marks".
 */
export interface AwarenessMark {
  id: number;
  tenantId: string;
  node: number | DiscussionNode;
  reactionType: 'awareness' | 'cry' | 'wiltedRose';
  user?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null);
  /**
   * Anonymous browser key used for testing awareness marks.
   */
  visitorKey?: string | null;
  /**
   * Unique node/reaction/user key used to make repeated reactions idempotent.
   */
  dedupeKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  tenantId: string;
  customerName: string;
  /**
   * Private. Used only if the bakery needs to follow up.
   */
  customerEmail?: string | null;
  reviewTone: 'loved_it' | 'suggestion';
  /**
   * 1 to 5 rating. Half-step values like 4.5 are allowed.
   */
  rating: number;
  title: string;
  body: string;
  /**
   * Optional public context, for example pickup order, catering, or cafe visit.
   */
  visitContext?: string | null;
  photos?: (number | Media)[] | null;
  publicStatus: 'under_review' | 'published' | 'declined';
  /**
   * Private admin note for spam, abuse, unverifiable claims, or unfair framing.
   */
  moderationNote?: string | null;
  /**
   * Public note when the bakery needs to add context, boundaries, or a factual correction.
   */
  fairnessNote?: string | null;
  responseStatus: 'listening' | 'investigating' | 'changed' | 'stood_firm' | 'closed';
  /**
   * Plain-text fallback for the public response.
   */
  businessResponse?: string | null;
  /**
   * Public bakery reply. Use this when the reply needs formatting.
   */
  businessResponseRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Public changes or decisions made in response to the review.
   */
  actionLog?:
    | {
        date: string;
        title: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blessings-network-owners".
 */
export interface BlessingsNetworkOwner {
  id: number;
  tenantId: string;
  publicStatus: 'under_review' | 'published' | 'declined';
  ownerName: string;
  title: string;
  businessName: string;
  /**
   * Short public label, for example cafe, bakery, catering, coffee, or retail.
   */
  businessType?: string | null;
  location: string;
  /**
   * Public website link.
   */
  websiteUrl?: string | null;
  /**
   * Public LinkedIn profile or company link.
   */
  linkedinUrl?: string | null;
  /**
   * Brief public description of what the business sells or serves.
   */
  description: string;
  /**
   * Longer public owner/business bio shown in the Learn more modal.
   */
  bio?: string | null;
  /**
   * Private. Used only if the site owner needs to verify the submission.
   */
  contactEmail?: string | null;
  /**
   * Lower numbers appear first in the owner showcase.
   */
  displayOrder?: number | null;
  /**
   * Private note for verification, edits, or declined submissions.
   */
  moderationNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blessings-network-questions".
 */
export interface BlessingsNetworkQuestion {
  id: number;
  tenantId: string;
  publicStatus: 'under_review' | 'published' | 'declined';
  title: string;
  body: string;
  category: string;
  questionStatus: 'seeking_advice' | 'answered' | 'archived';
  /**
   * Public asker name shown in the admin for context.
   */
  askedByName: string;
  /**
   * Lower numbers appear first on the page.
   */
  displayOrder?: number | null;
  /**
   * Private note for edits, sourcing, or follow-up.
   */
  moderationNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blessings-network-answers".
 */
export interface BlessingsNetworkAnswer {
  id: number;
  tenantId: string;
  question: number | BlessingsNetworkQuestion;
  owner: number | BlessingsNetworkOwner;
  publicStatus: 'under_review' | 'published' | 'declined';
  answer: string;
  /**
   * Short public summary of the most useful lesson in this reply.
   */
  practicalTakeaway?: string | null;
  /**
   * Lower numbers appear first under a question.
   */
  displayOrder?: number | null;
  /**
   * Private verification email from the reply form.
   */
  submittedByEmail?: string | null;
  /**
   * Stable key used to make public answer submission retries idempotent.
   */
  submissionKey?: string | null;
  publishedAt?: string | null;
  /**
   * Private note for verification, edits, or declined submissions.
   */
  moderationNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blessings-network-owner-posts".
 */
export interface BlessingsNetworkOwnerPost {
  id: number;
  tenantId: string;
  owner: number | BlessingsNetworkOwner;
  publicStatus: 'under_review' | 'published' | 'declined';
  title: string;
  /**
   * Short public grouping, for example leases, equipment, staffing, or pricing.
   */
  topic?: string | null;
  body: string;
  /**
   * Short public summary of the most useful lesson in this owner insight.
   */
  practicalTakeaway?: string | null;
  /**
   * Lower numbers appear first in Owner Insights.
   */
  displayOrder?: number | null;
  /**
   * Private verification email from the owner insight form.
   */
  submittedByEmail?: string | null;
  /**
   * Stable key used to make owner insight submission retries idempotent.
   */
  submissionKey?: string | null;
  publishedAt?: string | null;
  /**
   * Private note for verification, edits, or declined submissions.
   */
  moderationNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manual storefront flavor rotations. The active rotation controls which cookie products can be ordered individually; all other cookie flavors stay visible and link customers to /menu for catering trays.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flavor-rotations".
 */
export interface FlavorRotation {
  id: number;
  /**
   * Internal admin title, for example "May 2026 Cookie Rotation".
   */
  title: string;
  /**
   * Only one rotation should be active. Draft and archived rotations are invisible to customers.
   */
  status: 'draft' | 'active' | 'archived';
  /**
   * This keeps the model flexible for future seasonal or special flavor lineups without changing the storefront API.
   */
  rotationType: 'monthly' | 'seasonal' | 'special';
  /**
   * Optional name for this lineup, such as "May cookie rotation" or "Spring specials". Leave blank if you do not want to name the whole lineup.
   */
  displayLabel?: string | null;
  /**
   * How many flavors can be ordered individually for this rotation. Use 3 for the normal monthly model, or raise it before selecting flavors when the owner wants 5, 6, or a larger special lineup.
   */
  individualFlavorSlots: number;
  /**
   * Choose exactly the number of cookie products set in Rotation size. These are the only cookies customers can order one at a time; every other cookie remains visible and links to /menu for catering trays.
   */
  individualFlavors: (number | Product)[];
  /**
   * Short badge text for cookies included in this rotation. The default is fine unless you want wording like "Spring special" or "Available individually".
   */
  monthlyFlavorLabel?: string | null;
  /**
   * Short label shown beside the lock icon on non-rotation cookie cards.
   */
  lockedLabel?: string | null;
  /**
   * Plain-English explanation shown for non-rotation cookies. Keep it short so it fits on small cards.
   */
  lockedDescription?: string | null;
  /**
   * CTA label for catering-only cookies. The link destination remains /menu.
   */
  menuLinkLabel?: string | null;
  /**
   * Internal notes for the business owner. Not shown on the storefront; useful for future discount or seasonal planning.
   */
  ownerNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'email-verification-starts';
        value: number | EmailVerificationStart;
      } | null)
    | ({
        relationTo: 'phone-verification-starts';
        value: number | PhoneVerificationStart;
      } | null)
    | ({
        relationTo: 'discussion-nodes';
        value: number | DiscussionNode;
      } | null)
    | ({
        relationTo: 'discussion-edges';
        value: number | DiscussionEdge;
      } | null)
    | ({
        relationTo: 'awareness-marks';
        value: number | AwarenessMark;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'blessings-network-owners';
        value: number | BlessingsNetworkOwner;
      } | null)
    | ({
        relationTo: 'blessings-network-questions';
        value: number | BlessingsNetworkQuestion;
      } | null)
    | ({
        relationTo: 'blessings-network-answers';
        value: number | BlessingsNetworkAnswer;
      } | null)
    | ({
        relationTo: 'blessings-network-owner-posts';
        value: number | BlessingsNetworkOwnerPost;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'flavor-rotations';
        value: number | FlavorRotation;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: number | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: number | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: number | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'admins';
        value: number | Admin;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  phoneVerifiedAt?: T;
  stripeCustomerID?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-verification-starts_select".
 */
export interface EmailVerificationStartsSelect<T extends boolean = true> {
  key?: T;
  flow?: T;
  email?: T;
  codeHash?: T;
  attempts?: T;
  consumedAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-verification-starts_select".
 */
export interface PhoneVerificationStartsSelect<T extends boolean = true> {
  key?: T;
  flow?: T;
  phone?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussion-nodes_select".
 */
export interface DiscussionNodesSelect<T extends boolean = true> {
  tenantId?: T;
  isRoot?: T;
  rootNode?: T;
  author?: T;
  authorDisplayName?: T;
  type?: T;
  title?: T;
  content?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  searchText?: T;
  moderationStatus?: T;
  submissionKey?: T;
  moderationReason?: T;
  moderatedBy?: T;
  moderatedAt?: T;
  authorState?: T;
  reconsideredDueToNode?: T;
  supportCount?: T;
  challengeCount?: T;
  responseCount?: T;
  questionCount?: T;
  awarenessCount?: T;
  cryCount?: T;
  wiltedRoseCount?: T;
  childCount?: T;
  lastActivityAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussion-edges_select".
 */
export interface DiscussionEdgesSelect<T extends boolean = true> {
  tenantId?: T;
  rootNode?: T;
  fromNode?: T;
  toNode?: T;
  toBlockIds?:
    | T
    | {
        blockId?: T;
        id?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awareness-marks_select".
 */
export interface AwarenessMarksSelect<T extends boolean = true> {
  tenantId?: T;
  node?: T;
  reactionType?: T;
  user?: T;
  visitorKey?: T;
  dedupeKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  tenantId?: T;
  customerName?: T;
  customerEmail?: T;
  reviewTone?: T;
  rating?: T;
  title?: T;
  body?: T;
  visitContext?: T;
  photos?: T;
  publicStatus?: T;
  moderationNote?: T;
  fairnessNote?: T;
  responseStatus?: T;
  businessResponse?: T;
  businessResponseRichText?: T;
  actionLog?:
    | T
    | {
        date?: T;
        title?: T;
        detail?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blessings-network-owners_select".
 */
export interface BlessingsNetworkOwnersSelect<T extends boolean = true> {
  tenantId?: T;
  publicStatus?: T;
  ownerName?: T;
  title?: T;
  businessName?: T;
  businessType?: T;
  location?: T;
  websiteUrl?: T;
  linkedinUrl?: T;
  description?: T;
  bio?: T;
  contactEmail?: T;
  displayOrder?: T;
  moderationNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blessings-network-questions_select".
 */
export interface BlessingsNetworkQuestionsSelect<T extends boolean = true> {
  tenantId?: T;
  publicStatus?: T;
  title?: T;
  body?: T;
  category?: T;
  questionStatus?: T;
  askedByName?: T;
  displayOrder?: T;
  moderationNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blessings-network-answers_select".
 */
export interface BlessingsNetworkAnswersSelect<T extends boolean = true> {
  tenantId?: T;
  question?: T;
  owner?: T;
  publicStatus?: T;
  answer?: T;
  practicalTakeaway?: T;
  displayOrder?: T;
  submittedByEmail?: T;
  submissionKey?: T;
  publishedAt?: T;
  moderationNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blessings-network-owner-posts_select".
 */
export interface BlessingsNetworkOwnerPostsSelect<T extends boolean = true> {
  tenantId?: T;
  owner?: T;
  publicStatus?: T;
  title?: T;
  topic?: T;
  body?: T;
  practicalTakeaway?: T;
  displayOrder?: T;
  submittedByEmail?: T;
  submissionKey?: T;
  publishedAt?: T;
  moderationNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  authorName?: T;
  publishedOn?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flavor-rotations_select".
 */
export interface FlavorRotationsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  rotationType?: T;
  displayLabel?: T;
  individualFlavorSlots?: T;
  individualFlavors?: T;
  monthlyFlavorLabel?: T;
  lockedLabel?: T;
  lockedDescription?: T;
  menuLinkLabel?: T;
  ownerNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  menuOrder?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        poster?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  menuExpandedPitch?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  poster?:
    | T
    | {
        subtitle?: T;
        chips?:
          | T
          | {
              text?: T;
              id?: T;
            };
        label?: T;
        labelTone?: T;
        summary?: T;
        infoButtonLabel?: T;
        ingredientsNoteTitle?: T;
        ingredientsIntro?: T;
        receiptBody?: T;
        receiptTitle?: T;
        receiptWarnings?:
          | T
          | {
              tone?: T;
              label?: T;
              message?: T;
              id?: T;
            };
        ingredients?:
          | T
          | {
              name?: T;
              detail?: T;
              id?: T;
            };
      };
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  menuPortionLabel?: T;
  menuBehavior?: T;
  requiredSelectionCount?: T;
  selectableProducts?: T;
  relatedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        batchSelections?:
          | T
          | {
              product?: T;
              quantity?: T;
              id?: T;
            };
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  mergedSourceCartIDs?:
    | T
    | {
        sourceCartID?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        batchSelections?:
          | T
          | {
              product?: T;
              quantity?: T;
              id?: T;
            };
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  guestContactMethod?: T;
  guestContactValue?: T;
  accessToken?: T;
  ownerNotificationSentAt?: T;
  stripePaymentIntentID?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        batchSelections?:
          | T
          | {
              product?: T;
              quantity?: T;
              id?: T;
            };
        id?: T;
      };
  paymentMethod?: T;
  stripe?:
    | T
    | {
        customerID?: T;
        paymentIntentID?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  guestContactMethod?: T;
  guestContactValue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Manage the storefront brand name and logo in one place so the header can change without a code edit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand".
 */
export interface Brand {
  id: number;
  /**
   * Primary business name used for accessibility text and text-only fallbacks.
   */
  brandName: string;
  /**
   * Short alt text describing the logo image.
   */
  logoAlt?: string | null;
  /**
   * Use a public asset right away, or switch to Media once you upload a production-ready logo through the CMS.
   */
  logoSource?: ('publicPath' | 'mediaUpload') | null;
  /**
   * Path to a logo file in /public. This is useful for bootstrapping before the business owner starts managing uploaded assets.
   */
  logoPath?: string | null;
  /**
   * Select the uploaded logo from Media when you are ready to manage branding fully inside Payload.
   */
  logo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero copy shown at the top of /blog. Edit here to change what visitors read while they wait, without a code change.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page-content".
 */
export interface BlogPageContent {
  id: number;
  /**
   * Small uppercase label above the title (1–4 words).
   */
  eyebrow?: string | null;
  /**
   * Large headline shown in the hero.
   */
  title?: string | null;
  /**
   * Short paragraph below the title that sets expectations for the page (what it is for, that it is experimental, etc.).
   */
  summary?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Hero copy shown at the top of /discussion-board. Edit here to change what visitors read while they wait, without a code change.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussion-board-content".
 */
export interface DiscussionBoardContent {
  id: number;
  /**
   * Small uppercase label above the title (1–4 words).
   */
  eyebrow?: string | null;
  /**
   * Large headline shown in the hero.
   */
  title?: string | null;
  /**
   * Short paragraph below the title that sets expectations for the page (what it is for, that it is experimental, etc.).
   */
  summary?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand_select".
 */
export interface BrandSelect<T extends boolean = true> {
  brandName?: T;
  logoAlt?: T;
  logoSource?: T;
  logoPath?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page-content_select".
 */
export interface BlogPageContentSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discussion-board-content_select".
 */
export interface DiscussionBoardContentSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}